[package]
name = "cbz"
version = "1.0.1"
edition = "2024"
authors = ["tonymushah tonymushahdev06@yahoo.com"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tonymushah/cbz"
description = "Provide `cbz`, `cbt`, `cb7` reader and writers"
exclude = ["test-data", ".zed", ".github"]

[dependencies]
derive_builder = {version = "0.20", optional = true}
image = {version = "0.25", default-features = false}
log = {version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde-xml-rs = {version = "0.8", optional = true}
sevenz-rust2 = { version = "0.21", optional = true}
tar = {version = "0.4", optional = true}
thiserror = {version = "2.0", optional = true}
zip = {version = "8", optional = true}
derive_more = {version = "2", optional = true}
url = {version = "2", optional = true}
tempfile = { version = "3", optional = true }

[features]
default = []
cbz = ["image/jpeg", "image/png", "dep:thiserror", "dep:zip", "image/gif"]
cbt = ["dep:tar", "dep:thiserror", "derive_more/debug", "image/jpeg", "image/png", "image/gif"]
cb7 = ["dep:sevenz-rust2", "dep:tempfile", "dep:thiserror", "sevenz-rust2/compress", "derive_more/debug"]
log = ["dep:log"]
comicinfo = ["dep:serde", "dep:serde-xml-rs", "derive_more/from_str", "derive_more/display", "dep:thiserror", "derive_more/deref", "derive_more/into", "dep:derive_builder", "url/serde"]

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
image = { version = "0.25", default-features = true, features = ["rayon"] }
tempfile = "3"
fake = "5"
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
