[package]
name = "cbz"
version = "0.1.0"
edition = "2024"

[dependencies]
# derive_builder = "0.20"
image = {version = "0.25", default-features = false}
log = {version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde-xml-rs = {version = "0.8", optional = true}
sevenz-rust2 = { version = "0.20", optional = true}
tar = {version = "0.4", optional = true}
thiserror = {version = "2.0", optional = true}
zip = {version = "8", optional = true}
derive_more = {version = "2", optional = true}

[features]
default = ["cbz", "comicinfo"]
cbz = ["image/jpeg", "image/png", "dep:thiserror", "dep:zip", "image/gif"]
cbt = ["dep:tar"]
cb7z = ["dep:sevenz-rust2"]
log = ["dep:log"]
comicinfo = ["dep:serde", "dep:serde-xml-rs", "derive_more/from_str", "derive_more/display", "dep:thiserror", "derive_more/deref", "derive_more/into"]

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
image = { version = "0.25", default-features = true, features = ["rayon"] }
tempfile = "3"
fake = "5"
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
